name: Laravel CD

on:
  workflow_run:
    workflows: ["Laravel CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: 'MyPlesk'

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/vhosts/dimovr.com/api.dimovr.com/DimoLaravel/
            rm -rf public/storage
            git pull origin main
            composer install --optimize-autoloader --no-dev
            php artisan migrate
            php artisan storage:link
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan event:cache
            php artisan view:cache
            php artisan optimize
