name: Laravel CD

on:
  workflow_run:
    workflows: ["Laravel CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: 'MyPlesk'

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/vhosts/dimovr.com/api.dimovr.com/DimoLaravel/
            git pull origin main
            php artisan migrate
            composer install
